USE [master]
GO
/****** Object:  Database [SP_Medical_Group]    Script Date: 13/10/2021 17:48:16 ******/
CREATE DATABASE [SP_Medical_Group]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SP_Medical_Group', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SP_Medical_Group.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SP_Medical_Group_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SP_Medical_Group_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SP_Medical_Group] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SP_Medical_Group].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SP_Medical_Group] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET ARITHABORT OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [SP_Medical_Group] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SP_Medical_Group] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SP_Medical_Group] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET  ENABLE_BROKER 
GO
ALTER DATABASE [SP_Medical_Group] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SP_Medical_Group] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [SP_Medical_Group] SET  MULTI_USER 
GO
ALTER DATABASE [SP_Medical_Group] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SP_Medical_Group] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SP_Medical_Group] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SP_Medical_Group] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SP_Medical_Group] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [SP_Medical_Group] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [SP_Medical_Group] SET QUERY_STORE = OFF
GO
USE [SP_Medical_Group]
GO
/****** Object:  Table [dbo].[Clinica]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clinica](
	[Id_Clinica] [int] IDENTITY(1,1) NOT NULL,
	[Endereco] [varchar](300) NOT NULL,
	[Hora_Abertura] [time](7) NOT NULL,
	[Hora_Fechamento] [time](7) NOT NULL,
	[Cnpj] [varchar](20) NOT NULL,
	[Nome_Fantasia] [varchar](50) NOT NULL,
	[Razao_Social] [varchar](70) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Clinica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Cnpj] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Razao_Social] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Consulta]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Consulta](
	[Id_Consulta] [int] IDENTITY(1,1) NOT NULL,
	[Id_Prontuario] [int] NULL,
	[Id_Medico] [int] NULL,
	[Id_Status] [int] NULL,
	[Id_Clinica] [int] NULL,
	[Data_Consulta] [date] NOT NULL,
	[Descricao] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Consulta] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Especialidade]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Especialidade](
	[Id_Especialidade] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Especialidade] [varchar](200) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Especialidade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Nome_Especialidade] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Medico]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Medico](
	[Id_Medico] [int] IDENTITY(1,1) NOT NULL,
	[Id_Especialidade] [int] NULL,
	[Id_Clinica] [int] NULL,
	[Nome] [varchar](150) NOT NULL,
	[Crm] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Medico] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Crm] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Pacientes]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pacientes](
	[Id_Prontuario] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](500) NOT NULL,
	[Rg] [char](13) NOT NULL,
	[Cpf] [char](11) NOT NULL,
	[Data_Nascimento] [date] NOT NULL,
	[Telefone] [varchar](15) NULL,
	[Endereco] [varchar](300) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Prontuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Cpf] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Status_Consulta]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Status_Consulta](
	[Id_Status] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tipo_Usuario]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipo_Usuario](
	[Id_Tipo] [int] IDENTITY(1,1) NOT NULL,
	[Nome_Tipo] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuario]    Script Date: 13/10/2021 17:48:16 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[Id_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[Id_Tipo] [int] NULL,
	[Email] [varchar](250) NOT NULL,
	[Senha] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Consulta]  WITH CHECK ADD FOREIGN KEY([Id_Clinica])
REFERENCES [dbo].[Clinica] ([Id_Clinica])
GO
ALTER TABLE [dbo].[Consulta]  WITH CHECK ADD FOREIGN KEY([Id_Medico])
REFERENCES [dbo].[Medico] ([Id_Medico])
GO
ALTER TABLE [dbo].[Consulta]  WITH CHECK ADD FOREIGN KEY([Id_Prontuario])
REFERENCES [dbo].[Pacientes] ([Id_Prontuario])
GO
ALTER TABLE [dbo].[Consulta]  WITH CHECK ADD FOREIGN KEY([Id_Status])
REFERENCES [dbo].[Status_Consulta] ([Id_Status])
GO
ALTER TABLE [dbo].[Medico]  WITH CHECK ADD FOREIGN KEY([Id_Clinica])
REFERENCES [dbo].[Clinica] ([Id_Clinica])
GO
ALTER TABLE [dbo].[Medico]  WITH CHECK ADD FOREIGN KEY([Id_Especialidade])
REFERENCES [dbo].[Especialidade] ([Id_Especialidade])
GO
ALTER TABLE [dbo].[Usuario]  WITH CHECK ADD FOREIGN KEY([Id_Tipo])
REFERENCES [dbo].[Tipo_Usuario] ([Id_Tipo])
GO
USE [master]
GO
ALTER DATABASE [SP_Medical_Group] SET  READ_WRITE 
GO
